//Made by Rebecca Zhu
//Eblock objects to store any activity, can't use the word Activity since it is a reserved word so used Eblock instead

package com.example.myapplication;

import java.io.Serializable;

public class Eblock implements Serializable { //serializable interface allows data to be passed into the firebase database
    //variables to describe the activity
    private String date;
    private String teacher;
    private String description;
    private String id; //unique id generated by Firebase when created

    //allows Eblock objects to be set using the setters instead of instantiating a new object
    public Eblock(){

    }

    //constructor for Eblock object
    public Eblock(String date, String teacher, String description) {
        this.setDate(date);
        this.setTeacher(teacher);
        this.setDescription(description);
        this.setId(id);

    }

    //getter for Date
    public String getDate() {
        return date;
    }

    //setter for Date
    public void setDate(String date) {
        this.date = date;
    }

    //getter for teacher
    public String getTeacher() {
        return teacher;
    }

    //setter for teacher
    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    //getter for description
    public String getDescription() {
        return description;
    }

    //setter for description
    public void setDescription(String description) {
        this.description = description;
    }

    //getter for id
    public String getId() {
        return id;
    }

    //setter for id
    public void setId(String id) {
        this.id = id;
    }
}
